export const doctor = [
  {
    id: 1,
    name: "Dr. Priya Sharma",
    specialization: "Gynecologist",
    experience: "10 years",
    location: "Bhopal",
    rating: 4.7,
    image: "https://randomuser.me/api/portraits/women/44.jpg",
  },
  {
    id: 2,
    name: "Dr. Rahul Verma",
    specialization: "Cardiologist",
    experience: "15 years",
    location: "Delhi",
    rating: 4.8,
    image: "https://randomuser.me/api/portraits/men/32.jpg",
  },
  {
    id: 3,
    name: "Dr. Neha Gupta",
    specialization: "Dermatologist",
    experience: "8 years",
    location: "Indore",
    rating: 4.5,
    image: "https://randomuser.me/api/portraits/women/65.jpg",
  },
  {
    id: 4,
    name: "Dr. Amit Tiwari",
    specialization: "Orthopedic",
    experience: "12 years",
    location: "Lucknow",
    rating: 4.3,
    image: "https://randomuser.me/api/portraits/men/45.jpg",
  },
  {
    id: 5,
    name: "Dr. Sneha Kapoor",
    specialization: "Pediatrician",
    experience: "9 years",
    location: "Mumbai",
    rating: 4.6,
    image: "https://randomuser.me/api/portraits/women/50.jpg",
  },
  {
    id: 6,
    name: "Dr. Arjun Singh",
    specialization: "Neurologist",
    experience: "14 years",
    location: "Jaipur",
    rating: 4.7,
    image: "https://randomuser.me/api/portraits/men/56.jpg",
  },
  {
    id: 7,
    name: "Dr. Kavita Mehta",
    specialization: "Nutritionist",
    experience: "11 years",
    location: "Ahmedabad",
    rating: 4.4,
    image: "https://randomuser.me/api/portraits/women/72.jpg",
  },
  {
    id: 8,
    name: "Dr. Rohan Deshmukh",
    specialization: "Psychiatrist",
    experience: "13 years",
    location: "Pune",
    rating: 4.6,
    image: "https://randomuser.me/api/portraits/men/60.jpg",
  },
  {
    id: 9,
    name: "Dr. Anjali Mishra",
    specialization: "PCOS Specialist",
    experience: "10 years",
    location: "Varanasi",
    rating: 4.5,
    image: "https://randomuser.me/api/portraits/women/68.jpg",
  },
];